# Generated by Django 4.1.1 on 2022-10-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('dn_id', models.CharField(max_length=16)),
                ('machine_id', models.IntegerField()),
                ('created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
