# Generated by Django 4.1.1 on 2022-10-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='hostname',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
